app/models.py
from app import db
from werkzeug.security import generate_password_hash, check_password_hash

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)

    def set_password(self, password):
        password_hash = generate_password_hash(password)
        self.password_hash = password_hash
    
    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def get_user_id(username):
        user_id = User.query.filter_by(username=username).first()
        return user_id

    def __repr__(self):
        return f'<User user_id{self.id} username={self.username}>'


class AdminUser(db.Model):
    __tablename__ = 'admin_users'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), unique=True, nullable=False)

    def isAdmin(user_id):
        isAdminUser = AdminUser.query.filter_by(user_id=user_id).first()
        return isAdminUser != None

    def __repr__(self):
        return f'<AdminUser user_id={self.user_id}>'

app/Admin/__init__.py
from .routes import Admin as Admin_routes

app/Admin/routes.py
from flask import Blueprint
from . import views

Admin = Blueprint('Admin', __name__, template_folder="./templates", static_folder="./static")

@Admin.route('/')
def index():
    return views.adminPanel()

app/Admin/views.py
from flask import render_template, redirect, request, session, flash, url_for
from app.models import AdminUser

def has_admin_access(user_id):
    return AdminUser.isAdmin(user_id)


def adminPanel():
    if 'user_id' not in session:
        flash("Login to open admin panels", "error")
        return redirect(url_for("Taskly.auth.login"))
    if not has_admin_access(session['user_id']):
        flash("You don't have permissions for admin access", "error")
        return redirect(url_for("Taskly.dashboard.index"))
    return render_template('admin.html')

app/Prove/__init__.py
from .routes import Prove as Prove_routes


from .verify import verify_routes

Prove_routes.register_blueprint(verify_routes, url_prefix="/verify")

app/Prove/routes.py
from flask import Blueprint

Prove = Blueprint('Prove', __name__, template_folder='./templates')

app/Prove/verify/__init__.py
from .routes import verify as verify_routes

app/Prove/verify/routes.py
from flask import Blueprint
from . import views

verify = Blueprint("verify", __name__, template_folder="./templates", static_folder="./static")


@verify.route('/')
def index():
    return views.verify()

app/Prove/verify/views.py
from flask import render_template



def verify():
    return render_template('verify.html')

app/Taskly/__init__.py
from .routes import Taskly as Taskly_routes

from .auth import auth_routes
from .dashboard import dashboard_routes

Taskly_routes.register_blueprint(auth_routes, url_prefix='/auth')
Taskly_routes.register_blueprint(dashboard_routes, url_prefix='/dashboard')

app/Taskly/dashboard/__init__.py
from .routes import dashboard as dashboard_routes

app/Taskly/dashboard/routes.py
from flask import Blueprint
from . import views
from config import Config

dashboard = Blueprint('dashboard', __name__, template_folder='./templates', static_folder='./static')


@dashboard.route('/')
def index():
    if not Config.ENABLE_DASHBOARD:
        return views.dashboard_disabled()
    return views.dashboard()

app/Taskly/dashboard/views.py
from flask import Blueprint, render_template, session, redirect, url_for, flash
from utils import isLoggedIn


def dashboard_disabled():
    return render_template('dashboard_disabled.html')

@isLoggedIn
def dashboard():
    return render_template('dashboard.html', username=session.get('username'))

app/Taskly/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash

Taskly = Blueprint('Taskly', __name__)


@Taskly.route('/')
def index():
    return redirect(url_for('Taskly.dashboard.index'))

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
import os

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object('config.Config')
    app.config.from_pyfile('config.py', silent=True)

    db.init_app(app)
    migrate.init_app(app, db)  # << add this

    from .models import User  # Import your models here to register them with SQLAlchemy

    from .routes import main
    from .Taskly import Taskly_routes
    from .Prove import Prove_routes
    from .Admin import Admin_routes

    # Register the blueprints
    app.register_blueprint(main)
    app.register_blueprint(Taskly_routes, url_prefix="/taskly")
    app.register_blueprint(Prove_routes, url_prefix="/prove")
    app.register_blueprint(Admin_routes, url_prefix="/admin")

    return app

app/modules/dashboard/views.py
from flask import Blueprint, render_template, session, redirect, url_for, flash


def dashboard_disabled():
    return render_template('dashboard_disabled.html')

def dashboard():
    if 'user_id' not in session:
        flash('Please login first', 'error')
        return redirect(url_for('modules.auth.login'))

    return render_template('dashboard.html', username=session.get('username'))

app/routes.py
from flask import Blueprint
from . import views

main = Blueprint('main', __name__, template_folder='./templates', static_folder='./static')

@main.route('/')
def index():
    return views.index()

@main.route('/about')
def about():
    return views.about()

@main.route('/seeUsers')
def see_users():
    return views.see_users()

app/views.py
from flask import render_template, request, redirect, url_for, flash, session
from app import db
from .models import User
from config import Config

def index():
    return render_template('index.html')

def about():
    return render_template('about.html')

def see_users():
    users = User.query.all()
    return render_template('see_users.html', users=users, database_url=Config.SQLALCHEMY_DATABASE_URI)

app/templates/about.html
{% extends 'base.html' %}
{% block title %}About{% endblock %}
{% block content %}
<h2>About MyTasklyProve</h2>
<p>MyTasklyProve is a task management application that allows users to create, manage, and track their tasks efficiently. It provides a user-friendly interface and various features to enhance productivity.</p>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% block head %} {% endblock %}
    <title>{% block title %} {% endblock %} | MyTasklyProve</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    {% block style %} {% endblock %}
</head>
<body>
    <header>
        <h1>MyTasklyProve</h1>
        <nav>
            <ul>
                {% block navprimary %}
                <li><a href="{{ url_for('main.index') }}">Home</a></li>  
                <li><a href="{{ url_for('main.about') }}">About</a></li>
                <li><a href="{{ url_for('Admin.index') }}">Admin</a></li>
                {% endblock %}
                {% block navsecondary %}
                  {% if 'user_id' in session %}
                      {% block navsecondaryUser %}
                      <li><a href="{{ url_for('Taskly.dashboard.index') }}">Dashboard</a></li>
                      <li><a href="{{ url_for('Prove.verify.index')  }}">ProveMode</a></li>
                      <li><a href="{{ url_for('Taskly.auth.logout') }}">Logout</a></li>
                      {% endblock %}
                  {% else %}
                      {% block navsecondaryNoUser %}
                      <li><a href="{{ url_for('Taskly.auth.login') }}">Login</a></li>
                      <li><a href="{{ url_for('Taskly.auth.register') }}">Register</a></li>
                      {% endblock %}
                  {% endif %}
                {% endblock %}
            </ul>
        </nav>
    </header>

    <main>
        {% block content %} {% endblock %}
    </main>

    <div class="flashMessages" id="flashMessages">
     {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        <ul>
          {% for category, message in messages %}
            <li>
              {{ message }}
            </li>
          {% endfor %}
        </ul>
      {% endif %}
    {% endwith %}
    </div>

    <footer>
        <p>&copy; 2023 MyTasklyProve. All rights reserved.</p>
        {% block footer %} {% endblock %}
    </footer>

    <script src="{{ url_for('static', filename='js/base.js') }}"></script>
    {% block script %} {% endblock %}

</body>
</html>

app/templates/index.html
{% extends "base.html" %}



{% block title %}Home{% endblock %}

{% block content %}

    <h1>Welcome to MyTasklyProve</h1>
    <p>Track tasks. Get rewards. Prove your growth.</p>

{% endblock %}

app/templates/proveBase.html
{% extends 'base.html' %}
{% block title %}Prove Base{% endblock %}

{% block navprimary %}
<li><a href="{{ url_for('Taskly.dashboard.index') }}">Taskly</a></li>
{% endblock %}
{% block navsecondary %}
    {% if 'user_id' in session %}
        {% block navsecondaryUser %}
        <li><a href="{{ url_for('Prove.verify.index')  }}">ProveMode</a></li>
        <li><a href="{{ url_for('Taskly.auth.logout') }}">Logout</a></li>
        {% endblock %}
    {% else %}
        {% block navsecondaryNoUser %}
        <li><a href="{{ url_for('Taskly.auth.login') }}">Login</a></li>
        <li><a href="{{ url_for('Taskly.auth.register') }}">Register</a></li>
        {% endblock %}
    {% endif %}
{% endblock %}

app/templates/see_users.html
{% extends 'base.html' %}

{% block title %}See Users{% endblock %}

{% block content %}

<h1>Database: <small>{{ database_url }}</small></h1>

<h1>Users</h1>

{% if users %}
    <ul>
        {% for user in users %}
            <li>
                <strong>{{ user.username }}</strong>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No users found.</p>
{% endif %}

{% endblock %}